name: Build & Deploy

on:
  push:
    branches: [main, master]
  workflow_dispatch:
    inputs:
      seeder_type:
        description: "Run Database Seeders"
        required: false
        default: None
        type: choice
        options: [None, Fresh, Normal, User, Listing]

jobs:
  Deployment:
    runs-on: ovhcloud-master
    steps:
      - name: Pull Latest Code
        run: |
          cd "${{ vars.APP_PATH }}"
          git pull origin ${{ github.ref_name }}

      - name: Install Composer Dependencies
        run: |
          cd "${{ vars.APP_PATH }}"
          composer install --optimize-autoloader

      - name: Install NPM Dependencies
        run: |
          cd "${{ vars.APP_PATH }}"
          npm ci
          npm run build

      - name: Update Permissions
        run: |
          cd "${{ vars.APP_PATH }}"
          sudo chown -R ubuntu:www-data "${{ vars.APP_PATH }}/storage" "${{ vars.APP_PATH }}/bootstrap/cache"
          sudo chmod -R 775 "${{ vars.APP_PATH }}/storage" "${{ vars.APP_PATH }}/bootstrap/cache"

  Optimization:
    runs-on: ovhcloud-master
    needs: Deployment
    steps:
      - name: Cache Configurations
        run: |
          cd "${{ vars.APP_PATH }}"
          php artisan optimize:clear

      - name: Cache Events
        run: |
          cd "${{ vars.APP_PATH }}"
          php artisan event:cache

      - name: Cache Routes
        run: |
          cd "${{ vars.APP_PATH }}"
          php artisan route:cache

      - name: Cache Views
        run: |
          cd "${{ vars.APP_PATH }}"
          php artisan view:cache

  Migration:
    needs: Optimization
    runs-on: ovhcloud-master
    steps:
      - name: Migrate Database
        run: |
          cd "${{ vars.APP_PATH }}"
          php artisan migrate --force

  Seeder:
    needs: Migration
    runs-on: ovhcloud-master
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.seeder_type != 'None'
    steps:
      - name: Run Seeder
        run: |
          cd "${{ vars.APP_PATH }}"
          case "${{ github.event.inputs.seeder_type }}" in
            Fresh)
              php artisan migrate:fresh --seed --force
              ;;
            Normal)
              php artisan db:seed --force
              ;;
            User)
              php artisan db:seed --class=UserSeeder --force
              ;;
            Listing)
              php artisan db:seed --class=ListingSeeder --force
              ;;
            *)
              echo "No valid seeder_type provided"
              ;;
          esac
