name: Build & Deploy

on:
  push:
    branches: [main, master]

jobs:
  deploy:
    runs-on: ovhcloud-v1

    steps:
      - name: Pull Latest Code
        run: |
          cd /var/www/laravue
          git pull origin ${{ github.ref_name }}

      - name: Composer Install
        run: |
          cd /var/www/laravue
          composer install --no-dev --optimize-autoloader

      - name: NPM Build
        run: |
          cd /var/www/laravue
          npm ci
          npm run build

      # 4. Cleanup & Permissions
      - name: Optimization & Permissions
        run: |
          cd /var/www/laravue
          sudo chown -R ubuntu:www-data /var/www/laravue/storage /var/www/laravue/bootstrap/cache
          sudo chmod -R 775 /var/www/laravue/storage /var/www/laravue/bootstrap/cache